server:
  port: 8080

spring:
  mvc:
    async:
      request-timeout: 30000 #30 sec

nasa:
  api-key: {NASA_API_KEY: aKQYvWiVFkhaoSKQKtKmgE2XyOzd0gAUxWk69jnd}
  neo-feed-url: https://api.nasa.gov/neo/rest/v1/feed
  neo-look-up-url: https://api.nasa.gov/neo/rest/v1/neo
